server:
  port: 8081

spring:
  application:
    name: microservice-usuarios
  flyway:
    location: db.migration
  datasource:
    password: 'postgres'
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/usuarios
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
      show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true





