version: "3"

services:
  postgres:
    image: postgres:14.7
    container_name: "microservice-usuarios"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgres/data"
      - "./data/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 5432:5432
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
